Repository UMC-Inha/7th_Spring_Practice_Mission, pull requests merged in 2024-11, with the labels that each got.

#2 [5,6주차/제이] 워크북 제출합니다.
  build.gradle
  src/main/java/javalab/umc7th_mission/Umc7thMissionApplication.java
  src/main/java/javalab/umc7th_mission/config/QueryDSLConfig.java
  src/main/java/javalab/umc7th_mission/domain/FoodCategory.java
  src/main/java/javalab/umc7th_mission/domain/Member.java
  src/main/java/javalab/umc7th_mission/domain/Mission.java
  src/main/java/javalab/umc7th_mission/domain/Region.java
  src/main/java/javalab/umc7th_mission/domain/Review.java
  src/main/java/javalab/umc7th_mission/domain/ReviewImage.java
  src/main/java/javalab/umc7th_mission/domain/Store.java
  src/main/java/javalab/umc7th_mission/domain/Terms.java
  src/main/java/javalab/umc7th_mission/domain/common/BaseEntity.java
  src/main/java/javalab/umc7th_mission/domain/enums/Gender.java
  src/main/java/javalab/umc7th_mission/domain/enums/MemberStatus.java
  src/main/java/javalab/umc7th_mission/domain/enums/MissionStatus.java
  src/main/java/javalab/umc7th_mission/domain/enums/SocialType.java
  src/main/java/javalab/umc7th_mission/domain/mapping/MemberAgree.java
  src/main/java/javalab/umc7th_mission/domain/mapping/MemberMission.java
  src/main/java/javalab/umc7th_mission/domain/mapping/MemberPrefer.java
  src/main/java/javalab/umc7th_mission/repository/MemberMissionRepository/MemberMissionRepository.java
  src/main/java/javalab/umc7th_mission/repository/MemberMissionRepository/MemberMissionRepositoryCustom.java
  src/main/java/javalab/umc7th_mission/repository/MemberMissionRepository/MemberMissionRepositoryImpl.java
  src/main/java/javalab/umc7th_mission/repository/MemberRepository/MemberRepository.java
  src/main/java/javalab/umc7th_mission/repository/MemberRepository/MemberRepositoryCustom.java
  src/main/java/javalab/umc7th_mission/repository/MemberRepository/MemberRepositoryImpl.java
  src/main/java/javalab/umc7th_mission/repository/ReivewRepository/ReviewRepository.java
  src/main/java/javalab/umc7th_mission/repository/ReivewRepository/ReviewRepositoryCustom.java
  src/main/java/javalab/umc7th_mission/repository/ReivewRepository/ReviewRepositoryImpl.java
  src/main/java/javalab/umc7th_mission/repository/StoreRepository/StoreRepository.java
  src/main/java/javalab/umc7th_mission/repository/StoreRepository/StoreRepositoryCustom.java
  src/main/java/javalab/umc7th_mission/repository/StoreRepository/StoreRepositoryImpl.java
  src/main/java/javalab/umc7th_mission/service/StoreService/StoreQueryService.java
  src/main/java/javalab/umc7th_mission/service/StoreService/StoreQueryServiceImpl.java
  src/main/java/javalab/umc7th_mission/web/dto/HomePageDto.java
  src/main/java/javalab/umc7th_mission/web/dto/MissionDto.java
  src/main/java/javalab/umc7th_mission/web/dto/MyPageDto.java
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: Chapter05&06

#6 [5,6주차/수콩] 워크북 제출합니다.
  build.gradle
  src/main/java/javalab/umc7th_mission/study/config/QueryDSLConfig.java
  src/main/java/javalab/umc7th_mission/study/domain/Food.java
  src/main/java/javalab/umc7th_mission/study/domain/Member.java
  src/main/java/javalab/umc7th_mission/study/domain/Mission.java
  src/main/java/javalab/umc7th_mission/study/domain/Region.java
  src/main/java/javalab/umc7th_mission/study/domain/Restaurant.java
  src/main/java/javalab/umc7th_mission/study/domain/Review.java
  src/main/java/javalab/umc7th_mission/study/domain/Term.java
  src/main/java/javalab/umc7th_mission/study/domain/common/BaseEntity.java
  src/main/java/javalab/umc7th_mission/study/domain/enums/MemberStatus.java
  src/main/java/javalab/umc7th_mission/study/domain/enums/MissionStatus.java
  src/main/java/javalab/umc7th_mission/study/domain/enums/RestaurantStatus.java
  src/main/java/javalab/umc7th_mission/study/domain/enums/Role.java
  src/main/java/javalab/umc7th_mission/study/domain/enums/TermAgree.java
  src/main/java/javalab/umc7th_mission/study/domain/enums/TermRequired.java
  src/main/java/javalab/umc7th_mission/study/domain/mapping/MemberFood.java
  src/main/java/javalab/umc7th_mission/study/domain/mapping/MemberMission.java
  src/main/java/javalab/umc7th_mission/study/domain/mapping/MemberQuestion.java
  src/main/java/javalab/umc7th_mission/study/domain/mapping/MemberTerm.java
  src/main/java/javalab/umc7th_mission/study/dto/AvailableMissionDTO.java
  src/main/java/javalab/umc7th_mission/study/repository/MemberMissionRepository/MemberMissionRepository.java
  src/main/java/javalab/umc7th_mission/study/repository/MemberMissionRepository/MemberMissionRepositoryCustom.java
  src/main/java/javalab/umc7th_mission/study/repository/MemberMissionRepository/MemberMissionRepositoryImpl.java
  src/main/java/javalab/umc7th_mission/study/repository/MemberRepository/MemberRepository.java
  src/main/java/javalab/umc7th_mission/study/repository/MemberRepository/MemberRepositoryCustom.java
  src/main/java/javalab/umc7th_mission/study/repository/MemberRepository/MemberRepositoryImpl.java
  src/main/java/javalab/umc7th_mission/study/repository/MissionRepository/MissionRepository.java
  src/main/java/javalab/umc7th_mission/study/repository/MissionRepository/MissionRepositoryCustom.java
  src/main/java/javalab/umc7th_mission/study/repository/MissionRepository/MissionRepositoryImpl.java
  src/main/java/javalab/umc7th_mission/study/repository/RestaurantRepository/RestaurantRepository.java
  src/main/java/javalab/umc7th_mission/study/repository/RestaurantRepository/RestaurantRepositoryCustom.java
  src/main/java/javalab/umc7th_mission/study/repository/RestaurantRepository/RestaurantRepositoryImpl.java
  src/main/java/javalab/umc7th_mission/study/repository/ReviewRepository/ReviewRepository.java
  src/main/java/javalab/umc7th_mission/study/repository/ReviewRepository/ReviewRepositoryCustom.java
  src/main/java/javalab/umc7th_mission/study/repository/ReviewRepository/ReviewRepositoryImpl.java
  src/main/java/javalab/umc7th_mission/study/service/RestaurantService/RestaurantQueryService.java
  src/main/java/javalab/umc7th_mission/study/service/RestaurantService/RestaurantQueryServiceImpl.java
  src/main/resources/application.properties
  src/main/resources/application.yml
  src/test/java/javalab/umc7th_mission/study/service/RestaurantService/RestaurantQueryServiceImplTest.java
Labels: Chapter05&06

#8 [5,6주차/포비] 워크북 제출합니다.
  build.gradle
  src/main/java/javalab/umc7th_mission/Umc7thMissionApplication.java
  src/main/java/javalab/umc7th_mission/config/QueryDSLConfig.java
  src/main/java/javalab/umc7th_mission/domain/FoodCategory.java
  src/main/java/javalab/umc7th_mission/domain/Mission.java
  src/main/java/javalab/umc7th_mission/domain/Point.java
  src/main/java/javalab/umc7th_mission/domain/Region.java
  src/main/java/javalab/umc7th_mission/domain/Report.java
  src/main/java/javalab/umc7th_mission/domain/Review.java
  src/main/java/javalab/umc7th_mission/domain/Store.java
  src/main/java/javalab/umc7th_mission/domain/Terms.java
  src/main/java/javalab/umc7th_mission/domain/User.java
  src/main/java/javalab/umc7th_mission/domain/common/BaseEntity.java
  src/main/java/javalab/umc7th_mission/domain/enums/Gender.java
  src/main/java/javalab/umc7th_mission/domain/enums/MissionStatus.java
  src/main/java/javalab/umc7th_mission/domain/mapping/UserAgreedTerms.java
  src/main/java/javalab/umc7th_mission/domain/mapping/UserFoodCategory.java
  src/main/java/javalab/umc7th_mission/domain/mapping/UserMission.java
  src/main/java/javalab/umc7th_mission/dto/UserPointDTO.java
  src/main/java/javalab/umc7th_mission/repository/querydsl/mission/MissionCustomRepository.java
  src/main/java/javalab/umc7th_mission/repository/querydsl/mission/MissionCustomRepositoryImpl.java
  src/main/java/javalab/umc7th_mission/repository/querydsl/review/ReviewCustomRepository.java
  src/main/java/javalab/umc7th_mission/repository/querydsl/review/ReviewCustomRepositoryImpl.java
  src/main/java/javalab/umc7th_mission/repository/querydsl/user/UserCustomRepository.java
  src/main/java/javalab/umc7th_mission/repository/querydsl/user/UserCustomRepositoryImpl.java
  src/main/resources/application.yml
Labels: Chapter05&06

#4 [5,6주차/리키] 워크북 제출합니다.
  .gitignore
  src/main/java/javalab/global/entity/BaseEntity.java
  src/main/java/javalab/umc7th_mission/Umc7thMissionApplication.java
  src/main/java/javalab/umc7th_mission/domain/Category.java
  src/main/java/javalab/umc7th_mission/domain/Member.java
  src/main/java/javalab/umc7th_mission/domain/Mission.java
  src/main/java/javalab/umc7th_mission/domain/Notification.java
  src/main/java/javalab/umc7th_mission/domain/Restaurant.java
  src/main/java/javalab/umc7th_mission/domain/Review.java
  src/main/java/javalab/umc7th_mission/domain/enums/Gender.java
  src/main/java/javalab/umc7th_mission/domain/enums/Status.java
  src/main/java/javalab/umc7th_mission/domain/mapping/MemberMission.java
  src/main/java/javalab/umc7th_mission/domain/mapping/PreferedCategory.java
  src/main/java/javalab/umc7th_mission/domain/mapping/RestaurantCategory.java
  src/main/java/javalab/umc7th_mission/domain/photo/RestaurantPhoto.java
  src/main/java/javalab/umc7th_mission/domain/photo/ReviewPhoto.java
  src/main/resources/application.properties
Labels: Chapter05&06

#5 [5,6주차/피우] 워크북 제출합니다.
  .gitignore
  build.gradle
  src/main/java/javalab/umc7th_mission/Umc7thMissionApplication.java
  src/main/java/javalab/umc7th_mission/config/QueryDSLConfig.java
  src/main/java/javalab/umc7th_mission/domain/Alarm.java
  src/main/java/javalab/umc7th_mission/domain/FoodCategory.java
  src/main/java/javalab/umc7th_mission/domain/Member.java
  src/main/java/javalab/umc7th_mission/domain/Mission.java
  src/main/java/javalab/umc7th_mission/domain/Region.java
  src/main/java/javalab/umc7th_mission/domain/Restaurant.java
  src/main/java/javalab/umc7th_mission/domain/Review.java
  src/main/java/javalab/umc7th_mission/domain/ReviewImage.java
  src/main/java/javalab/umc7th_mission/domain/Term.java
  src/main/java/javalab/umc7th_mission/domain/common/BaseEntity.java
  src/main/java/javalab/umc7th_mission/domain/enums/AlarmType.java
  src/main/java/javalab/umc7th_mission/domain/enums/Gender.java
  src/main/java/javalab/umc7th_mission/domain/enums/MemberStatus.java
  src/main/java/javalab/umc7th_mission/domain/enums/MissionStatus.java
  src/main/java/javalab/umc7th_mission/domain/enums/SocialType.java
  src/main/java/javalab/umc7th_mission/domain/mapping/MemberFood.java
  src/main/java/javalab/umc7th_mission/domain/mapping/MemberMission.java
  src/main/java/javalab/umc7th_mission/domain/mapping/MemberTerm.java
  src/main/java/javalab/umc7th_mission/repository/MemberMissionRepository/MemberMissionRepository.java
  src/main/java/javalab/umc7th_mission/repository/MemberMissionRepository/MemberMissionRepositoryCustom.java
  src/main/java/javalab/umc7th_mission/repository/MemberMissionRepository/MemberMissionRepositoryImpl.java
  src/main/java/javalab/umc7th_mission/repository/MemberRepository/MemberRepository.java
  src/main/java/javalab/umc7th_mission/repository/MemberRepository/MemberRepositoryCustom.java
  src/main/java/javalab/umc7th_mission/repository/MemberRepository/MemberRepositoryImpl.java
  src/main/java/javalab/umc7th_mission/repository/MissionRepository/MissionRepository.java
  src/main/java/javalab/umc7th_mission/repository/MissionRepository/MissionRepositoryCustom.java
  src/main/java/javalab/umc7th_mission/repository/MissionRepository/MissionRepositoryImpl.java
  src/main/java/javalab/umc7th_mission/repository/ReviewRepository/ReviewRepository.java
  src/main/java/javalab/umc7th_mission/repository/ReviewRepository/ReviewRepositoryCustom.java
  src/main/java/javalab/umc7th_mission/repository/ReviewRepository/ReviewRepositoryImpl.java
  src/main/java/javalab/umc7th_mission/web/dto/MissionDTO.java
  src/main/java/javalab/umc7th_mission/web/dto/MyPageDTO.java
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: Chapter05&06

#3 [5,6주차/모리] 워크북 제출합니다.
  build.gradle
  src/main/java/javalab/umc7th_mission/Umc7thMissionApplication.java
  src/main/java/javalab/umc7th_mission/config/QueryDSLConfig.java
  src/main/java/javalab/umc7th_mission/domain/FoodCategory.java
  src/main/java/javalab/umc7th_mission/domain/Member.java
  src/main/java/javalab/umc7th_mission/domain/Mission.java
  src/main/java/javalab/umc7th_mission/domain/Notification.java
  src/main/java/javalab/umc7th_mission/domain/Question.java
  src/main/java/javalab/umc7th_mission/domain/QuestionImage.java
  src/main/java/javalab/umc7th_mission/domain/Region.java
  src/main/java/javalab/umc7th_mission/domain/Review.java
  src/main/java/javalab/umc7th_mission/domain/ReviewImage.java
  src/main/java/javalab/umc7th_mission/domain/Store.java
  src/main/java/javalab/umc7th_mission/domain/Terms.java
  src/main/java/javalab/umc7th_mission/domain/common/BaseEntity.java
  src/main/java/javalab/umc7th_mission/domain/enums/Gender.java
  src/main/java/javalab/umc7th_mission/domain/enums/MemberStatus.java
  src/main/java/javalab/umc7th_mission/domain/enums/MissionStatus.java
  src/main/java/javalab/umc7th_mission/domain/mapping/MemberAddress.java
  src/main/java/javalab/umc7th_mission/domain/mapping/MemberAgree.java
  src/main/java/javalab/umc7th_mission/domain/mapping/MemberMission.java
  src/main/java/javalab/umc7th_mission/domain/mapping/MemberNotification.java
  src/main/java/javalab/umc7th_mission/domain/mapping/MemberPrefer.java
  src/main/java/javalab/umc7th_mission/domain/mapping/StoreAddress.java
  src/main/java/javalab/umc7th_mission/domain/mapping/StoreCategory.java
  src/main/java/javalab/umc7th_mission/repository/MemberMissionRepository/MemberMissionRepository.java
  src/main/java/javalab/umc7th_mission/repository/MemberMissionRepository/MemberMissionRepositoryCustom.java
  src/main/java/javalab/umc7th_mission/repository/MemberMissionRepository/MemberMissionRepositoryImpl.java
  src/main/java/javalab/umc7th_mission/repository/MemberRepository/MemberRepository.java
  src/main/java/javalab/umc7th_mission/repository/MemberRepository/MemberRepositoryCustom.java
  src/main/java/javalab/umc7th_mission/repository/MemberRepository/MemberRepositoryImpl.java
  src/main/java/javalab/umc7th_mission/repository/ReviewRepository/ReviewRepository.java
  src/main/java/javalab/umc7th_mission/repository/ReviewRepository/ReviewRepositoryCustom.java
  src/main/java/javalab/umc7th_mission/repository/ReviewRepository/ReviewRepositoryImpl.java
  src/main/java/javalab/umc7th_mission/repository/StoreRepository/StoreRepository.java
  src/main/java/javalab/umc7th_mission/repository/StoreRepository/StoreRepositoryCustom.java
  src/main/java/javalab/umc7th_mission/repository/StoreRepository/StoreRepositoryImpl.java
  src/main/java/javalab/umc7th_mission/web/dto/MemberInfoDto.java
Labels: Chapter05&06

#12 [5,6주차/져니] 워크북 제출합니다.
  src/main/java/javalab/umc7th_mission/config/QueryDSLConfig.java
  src/main/java/javalab/umc7th_mission/domain/AlarmTerms.java
  src/main/java/javalab/umc7th_mission/domain/FoodCategory.java
  src/main/java/javalab/umc7th_mission/domain/Member.java
  src/main/java/javalab/umc7th_mission/domain/Mission.java
  src/main/java/javalab/umc7th_mission/domain/Region.java
  src/main/java/javalab/umc7th_mission/domain/Review.java
  src/main/java/javalab/umc7th_mission/domain/ReviewImage.java
  src/main/java/javalab/umc7th_mission/domain/Store.java
  src/main/java/javalab/umc7th_mission/domain/Terms.java
  src/main/java/javalab/umc7th_mission/domain/common/BaseEntity.java
  src/main/java/javalab/umc7th_mission/domain/enums/Gender.java
  src/main/java/javalab/umc7th_mission/domain/enums/MissionStatus.java
  src/main/java/javalab/umc7th_mission/domain/mapping/MemberAgree.java
  src/main/java/javalab/umc7th_mission/domain/mapping/MemberAlarm.java
  src/main/java/javalab/umc7th_mission/domain/mapping/MemberMission.java
  src/main/java/javalab/umc7th_mission/domain/mapping/MemberPrefer.java
  src/main/java/javalab/umc7th_mission/repository/MemberMissionRepository/MemberMissionRepository.java
  src/main/java/javalab/umc7th_mission/repository/MemberMissionRepository/MemberMissionRepositoryCustom.java
  src/main/java/javalab/umc7th_mission/repository/MemberMissionRepository/MemberMissionRepositoryImpl.java
  src/main/java/javalab/umc7th_mission/repository/MemberRepository/MemberRepository.java
  src/main/java/javalab/umc7th_mission/repository/MemberRepository/MemberRepositoryCustom.java
  src/main/java/javalab/umc7th_mission/repository/MemberRepository/MemberRepositoryImpl.java
  src/main/java/javalab/umc7th_mission/repository/ReviewRepository/ReviewRepository.java
  src/main/java/javalab/umc7th_mission/repository/ReviewRepository/ReviewRepositoryCustom.java
  src/main/java/javalab/umc7th_mission/repository/ReviewRepository/ReviewRepositoryImpl.java
  src/main/java/javalab/umc7th_mission/repository/StoreRepository/StoreRepository.java
  src/main/java/javalab/umc7th_mission/repository/StoreRepository/StoreRepositoryCustom.java
  src/main/java/javalab/umc7th_mission/repository/StoreRepository/StoreRepositoryImpl.java
  src/main/java/javalab/umc7th_mission/service/StoreService/StoreQueryService.java
  src/main/java/javalab/umc7th_mission/service/StoreService/StoreQueryServiceImpl.java
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: Chapter05&06

#10 [5,6주차/앨빈] 워크북 제출합니다.
  src/main/java/javalab/umc7th_mission/domian/alarm/Alarm.java
  src/main/java/javalab/umc7th_mission/domian/category/Category.java
  src/main/java/javalab/umc7th_mission/domian/common/BaseEntity.java
  src/main/java/javalab/umc7th_mission/domian/mapping/MemberCategory.java
  src/main/java/javalab/umc7th_mission/domian/mapping/MemberMission.java
  src/main/java/javalab/umc7th_mission/domian/member/Gender.java
  src/main/java/javalab/umc7th_mission/domian/member/Member.java
  src/main/java/javalab/umc7th_mission/domian/member/dto/ResponseDto.java
  src/main/java/javalab/umc7th_mission/domian/mission/Mission.java
  src/main/java/javalab/umc7th_mission/domian/mission/Status.java
  src/main/java/javalab/umc7th_mission/domian/mission/dto/MissionResponse.java
  src/main/java/javalab/umc7th_mission/domian/review/Review.java
  src/main/java/javalab/umc7th_mission/domian/store/Store.java
  src/main/java/javalab/umc7th_mission/repository/member/MemberCustomRepositoryImpl.java
  src/main/java/javalab/umc7th_mission/repository/member/memberCustomRepository.java
  src/main/java/javalab/umc7th_mission/repository/mission/MissionCustomRepository.java
  src/main/java/javalab/umc7th_mission/repository/mission/MissionCustomRepositoryImpl.java
  src/main/java/javalab/umc7th_mission/repository/review/ReviewCustomRepository.java
  src/main/java/javalab/umc7th_mission/repository/review/ReviewCustomRepositoryImpl.java
Labels: Chapter05&06

#7 [5,6주차/공공] 워크북 제출합니다.
  build.gradle
  src/main/java/javalab/umc7th_mission/config/QueryDSLConfig.java
  src/main/java/javalab/umc7th_mission/domain/Member.java
  src/main/java/javalab/umc7th_mission/domain/Mission.java
  src/main/java/javalab/umc7th_mission/domain/Region.java
  src/main/java/javalab/umc7th_mission/domain/Review.java
  src/main/java/javalab/umc7th_mission/domain/Store.java
  src/main/java/javalab/umc7th_mission/domain/Terms.java
  src/main/java/javalab/umc7th_mission/domain/common/BaseEntity.java
  src/main/java/javalab/umc7th_mission/domain/enums/Gender.java
  src/main/java/javalab/umc7th_mission/domain/enums/MemberStatus.java
  src/main/java/javalab/umc7th_mission/domain/enums/MissionStatus.java
  src/main/java/javalab/umc7th_mission/domain/enums/SocialType.java
  src/main/java/javalab/umc7th_mission/domain/foodCategory.java
  src/main/java/javalab/umc7th_mission/domain/mapping/MemberAgree.java
  src/main/java/javalab/umc7th_mission/domain/mapping/MemberMission.java
  src/main/java/javalab/umc7th_mission/domain/mapping/MemberPrefer.java
  src/main/java/javalab/umc7th_mission/repository/MemberMissionRepository/MemberMissionRepository.java
  src/main/java/javalab/umc7th_mission/repository/MemberMissionRepository/MemberMissionRepositoryCustom.java
  src/main/java/javalab/umc7th_mission/repository/MemberMissionRepository/MemberMissionRepositoryImpl.java
  src/main/java/javalab/umc7th_mission/repository/MemberRepository/MemberRepository.java
  src/main/java/javalab/umc7th_mission/repository/MemberRepository/MemberRepositoryCustom.java
  src/main/java/javalab/umc7th_mission/repository/MemberRepository/MemberRepositoryImpl.java
  src/main/java/javalab/umc7th_mission/repository/MissionRepository/MissionRepository.java
  src/main/java/javalab/umc7th_mission/repository/MissionRepository/MissionRepositoryCustom.java
  src/main/java/javalab/umc7th_mission/repository/MissionRepository/MissionRepositoryImpl.java
  src/main/java/javalab/umc7th_mission/repository/ReviewRepository/ReviewRepository.java
  src/main/java/javalab/umc7th_mission/repository/ReviewRepository/ReviewRepositoryCustom.java
  src/main/java/javalab/umc7th_mission/repository/ReviewRepository/ReviewRepositoryImpl.java
  src/main/java/javalab/umc7th_mission/repository/StoreRepository/StoreRepository.java
  src/main/java/javalab/umc7th_mission/repository/StoreRepository/StoreRepositoryCustom.java
  src/main/java/javalab/umc7th_mission/repository/StoreRepository/StoreRepositoryImpl.java
  src/main/java/javalab/umc7th_mission/web/dto/MemberDto.java
  src/main/java/javalab/umc7th_mission/web/dto/MissionDto.java
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: Chapter05&06

#11 [5,6주차/데이브] 워크북 제출합니다.
  build.gradle
  src/main/java/javalab/umc7th_mission/config/QueryDslConfig.java
  src/main/java/javalab/umc7th_mission/domain/common/BaseEntity.java
  src/main/java/javalab/umc7th_mission/domain/foodcategory/FoodCategory.java
  src/main/java/javalab/umc7th_mission/domain/member/Gender.java
  src/main/java/javalab/umc7th_mission/domain/member/Member.java
  src/main/java/javalab/umc7th_mission/domain/member/MemberStatus.java
  src/main/java/javalab/umc7th_mission/domain/member/SocialType.java
  src/main/java/javalab/umc7th_mission/domain/member/repository/CustomMemberRepository.java
  src/main/java/javalab/umc7th_mission/domain/member/repository/CustomMemberRepositoryImpl.java
  src/main/java/javalab/umc7th_mission/domain/memberagree/MemberAgree.java
  src/main/java/javalab/umc7th_mission/domain/membermission/MemberMission.java
  src/main/java/javalab/umc7th_mission/domain/memberprefer/MemberPrefer.java
  src/main/java/javalab/umc7th_mission/domain/mission/Mission.java
  src/main/java/javalab/umc7th_mission/domain/mission/MissionStatus.java
  src/main/java/javalab/umc7th_mission/domain/mission/repository/CustomMissionRepository.java
  src/main/java/javalab/umc7th_mission/domain/mission/repository/MissionCustomRepositoryImpl.java
  src/main/java/javalab/umc7th_mission/domain/region/Region.java
  src/main/java/javalab/umc7th_mission/domain/review/Review.java
  src/main/java/javalab/umc7th_mission/domain/review/ReviewImage.java
  src/main/java/javalab/umc7th_mission/domain/store/Store.java
  src/main/java/javalab/umc7th_mission/domain/store/repository/CustomStoreRepository.java
  src/main/java/javalab/umc7th_mission/domain/store/repository/StoreRepositoryImpl.java
  src/main/java/javalab/umc7th_mission/domain/terms/Terms.java
Labels: Chapter05&06

#25 [7주차/앨빈] 워크북 제출합니다.
  src/main/java/javalab/umc7th_mission/apipayload/ApiResponse.java
  src/main/java/javalab/umc7th_mission/apipayload/code/BaseCode.java
  src/main/java/javalab/umc7th_mission/apipayload/code/BaseErrorCode.java
  src/main/java/javalab/umc7th_mission/apipayload/code/ErrorReasonDTO.java
  src/main/java/javalab/umc7th_mission/apipayload/code/ReasonDTO.java
  src/main/java/javalab/umc7th_mission/apipayload/code/code/ErrorStatus.java
  src/main/java/javalab/umc7th_mission/apipayload/code/code/SuccessStatus.java
  src/main/java/javalab/umc7th_mission/apipayload/exception/ExceptionAdvice.java
  src/main/java/javalab/umc7th_mission/apipayload/exception/GeneralException.java
  src/main/java/javalab/umc7th_mission/apipayload/exception/handler/TempHandler.java
  src/main/java/javalab/umc7th_mission/config/QueryDSLConfig.java
  src/main/java/javalab/umc7th_mission/converter/TempConverter.java
  src/main/java/javalab/umc7th_mission/service/tempService/TempCommandService.java
  src/main/java/javalab/umc7th_mission/service/tempService/TempCommandServiceimpl.java
  src/main/java/javalab/umc7th_mission/service/tempService/TempQueryService.java
  src/main/java/javalab/umc7th_mission/service/tempService/TempQueryServiceImpl.java
  src/main/java/javalab/umc7th_mission/web/controller/TempRestController.java
  src/main/java/javalab/umc7th_mission/web/dto/TempRequest.java
  src/main/java/javalab/umc7th_mission/web/dto/TempResponse.java
Labels: Chapter07

#17 [7주차/공공] 워크북 제출합니다.
  build.gradle
  src/main/java/javalab/umc7th_mission/apiPayload/ApiResponse.java
  src/main/java/javalab/umc7th_mission/apiPayload/code/BaseCode.java
  src/main/java/javalab/umc7th_mission/apiPayload/code/BaseErrorCode.java
  src/main/java/javalab/umc7th_mission/apiPayload/code/ErrorReasonDTO.java
  src/main/java/javalab/umc7th_mission/apiPayload/code/ReasonDTO.java
  src/main/java/javalab/umc7th_mission/apiPayload/code/status/ErrorStatus.java
  src/main/java/javalab/umc7th_mission/apiPayload/code/status/SuccessStatus.java
  src/main/java/javalab/umc7th_mission/apiPayload/converter/TempConverter.java
  src/main/java/javalab/umc7th_mission/apiPayload/exception/ExceptionAdvice.java
  src/main/java/javalab/umc7th_mission/apiPayload/exception/GeneralException.java
  src/main/java/javalab/umc7th_mission/apiPayload/exception/handler/TempHandler.java
  src/main/java/javalab/umc7th_mission/controller/TempController.java
  src/main/java/javalab/umc7th_mission/converter/TempConverter.java
  src/main/java/javalab/umc7th_mission/dto/TempRequest.java
  src/main/java/javalab/umc7th_mission/dto/TempResponse.java
  src/main/java/javalab/umc7th_mission/service/TempService/TempCommandService.java
  src/main/java/javalab/umc7th_mission/service/TempService/TempCommandServiceImpl.java
  src/main/java/javalab/umc7th_mission/service/TempService/TempQueryService.java
  src/main/java/javalab/umc7th_mission/service/TempService/TempQueryServiceImpl.java
Labels: Chapter07

#16 [7주차/포비] 워크북 제출합니다.
  src/main/java/javalab/umc7th_mission/global/ApiResponse.java
  src/main/java/javalab/umc7th_mission/global/BaseCode.java
  src/main/java/javalab/umc7th_mission/global/BaseErrorCode.java
  src/main/java/javalab/umc7th_mission/global/ErrorReasonDTO.java
  src/main/java/javalab/umc7th_mission/global/ReasonDTO.java
  src/main/java/javalab/umc7th_mission/global/code/ErrorStatus.java
  src/main/java/javalab/umc7th_mission/global/code/SuccessStatus.java
  src/main/java/javalab/umc7th_mission/global/exception/ExceptionAdvice.java
  src/main/java/javalab/umc7th_mission/global/exception/GeneralException.java
  src/main/java/javalab/umc7th_mission/global/exception/handler/TempHandler.java
  src/main/java/javalab/umc7th_mission/web/controller/TempRestController.java
  src/main/java/javalab/umc7th_mission/web/converter/TempConverter.java
  src/main/java/javalab/umc7th_mission/web/dto/TempRequest.java
  src/main/java/javalab/umc7th_mission/web/dto/TempResponse.java
  src/main/java/javalab/umc7th_mission/web/service/TempCommandService.java
  src/main/java/javalab/umc7th_mission/web/service/TempCommandServiceImpl.java
  src/main/java/javalab/umc7th_mission/web/service/TempQueryService.java
  src/main/java/javalab/umc7th_mission/web/service/TempQueryServiceImpl.java
Labels: Chapter07

#15 [7주차/수콩] 워크북 제출합니다.
  build.gradle
  src/main/java/javalab/umc7th_mission/study/apiPayload/ApiResponse.java
  src/main/java/javalab/umc7th_mission/study/apiPayload/code/BaseCode.java
  src/main/java/javalab/umc7th_mission/study/apiPayload/code/BaseErrorCode.java
  src/main/java/javalab/umc7th_mission/study/apiPayload/code/ErrorReasonDTO.java
  src/main/java/javalab/umc7th_mission/study/apiPayload/code/ReasonDTO.java
  src/main/java/javalab/umc7th_mission/study/apiPayload/code/status/ErrorStatus.java
  src/main/java/javalab/umc7th_mission/study/apiPayload/code/status/SuccessStatus.java
  src/main/java/javalab/umc7th_mission/study/apiPayload/exception/ExceptionAdvice.java
  src/main/java/javalab/umc7th_mission/study/apiPayload/exception/GeneralException.java
  src/main/java/javalab/umc7th_mission/study/apiPayload/exception/handler/TempHandler.java
  src/main/java/javalab/umc7th_mission/study/controller/TempController.java
  src/main/java/javalab/umc7th_mission/study/converter/TempConverter.java
  src/main/java/javalab/umc7th_mission/study/dto/TempRequest.java
  src/main/java/javalab/umc7th_mission/study/dto/TempResponse.java
  src/main/java/javalab/umc7th_mission/study/service/TempService/TempCommandService.java
  src/main/java/javalab/umc7th_mission/study/service/TempService/TempCommandServiceImpl.java
  src/main/java/javalab/umc7th_mission/study/service/TempService/TempQueryService.java
  src/main/java/javalab/umc7th_mission/study/service/TempService/TempQueryServiceImpl.java
Labels: Chapter07

#14 [7주차/제이] 워크북 제출합니다.
  build.gradle
  src/main/generated/ext/javalab/umc7th_mission/domain/QFoodCategory.java
  src/main/generated/ext/javalab/umc7th_mission/domain/QMember.java
  src/main/generated/ext/javalab/umc7th_mission/domain/QMission.java
  src/main/generated/ext/javalab/umc7th_mission/domain/QRegion.java
  src/main/generated/ext/javalab/umc7th_mission/domain/QReview.java
  src/main/generated/ext/javalab/umc7th_mission/domain/QReviewImage.java
  src/main/generated/ext/javalab/umc7th_mission/domain/QStore.java
  src/main/generated/ext/javalab/umc7th_mission/domain/QTerms.java
  src/main/generated/ext/javalab/umc7th_mission/domain/common/QBaseEntity.java
  src/main/generated/ext/javalab/umc7th_mission/domain/mapping/QMemberAgree.java
  src/main/generated/ext/javalab/umc7th_mission/domain/mapping/QMemberMission.java
  src/main/generated/ext/javalab/umc7th_mission/domain/mapping/QMemberPrefer.java
  src/main/java/javalab/umc7th_mission/Umc7thMissionApplication.java
  src/main/java/javalab/umc7th_mission/apiPayload/ApiResponse.java
  src/main/java/javalab/umc7th_mission/apiPayload/code/BaseCode.java
  src/main/java/javalab/umc7th_mission/apiPayload/code/BaseErrorCode.java
  src/main/java/javalab/umc7th_mission/apiPayload/code/ErrorReasonDTO.java
  src/main/java/javalab/umc7th_mission/apiPayload/code/ReasonDTO.java
  src/main/java/javalab/umc7th_mission/apiPayload/code/status/ErrorStatus.java
  src/main/java/javalab/umc7th_mission/apiPayload/code/status/SuccessStatus.java
  src/main/java/javalab/umc7th_mission/apiPayload/exception/ExceptionAdvice.java
  src/main/java/javalab/umc7th_mission/apiPayload/exception/GeneralException.java
  src/main/java/javalab/umc7th_mission/apiPayload/exception/handler/TempHandler.java
  src/main/java/javalab/umc7th_mission/converter/TempConverter.java
  src/main/java/javalab/umc7th_mission/domain/Member.java
  src/main/java/javalab/umc7th_mission/repository/ReivewRepository/ReviewRepository.java
  src/main/java/javalab/umc7th_mission/service/TempService/TempCommandService.java
  src/main/java/javalab/umc7th_mission/service/TempService/TempCommandServiceImpl.java
  src/main/java/javalab/umc7th_mission/service/TempService/TempQueryService.java
  src/main/java/javalab/umc7th_mission/service/TempService/TempQueryServiceImpl.java
  src/main/java/javalab/umc7th_mission/web/controller/TempRestController.java
  src/main/java/javalab/umc7th_mission/web/dto/TempRequest.java
  src/main/java/javalab/umc7th_mission/web/dto/TempResponse.java
Labels: Chapter07

#18 [7주차/모리] 워크북 제출합니다.
  build.gradle
  src/main/java/javalab/umc7th_mission/Umc7thMissionApplication.java
  src/main/java/javalab/umc7th_mission/apiPayload/ApiResponse.java
  src/main/java/javalab/umc7th_mission/apiPayload/BaseCode.java
  src/main/java/javalab/umc7th_mission/apiPayload/BaseErrorCode.java
  src/main/java/javalab/umc7th_mission/apiPayload/ErrorReasonDTO.java
  src/main/java/javalab/umc7th_mission/apiPayload/ReasonDTO.java
  src/main/java/javalab/umc7th_mission/apiPayload/code/status/ErrorStatus.java
  src/main/java/javalab/umc7th_mission/apiPayload/code/status/SuccessStatus.java
  src/main/java/javalab/umc7th_mission/apiPayload/exception/ExceptionAdvice.java
  src/main/java/javalab/umc7th_mission/apiPayload/exception/GeneralException.java
  src/main/java/javalab/umc7th_mission/apiPayload/exception/handler/TempHandler.java
  src/main/java/javalab/umc7th_mission/config/QueryDSLConfig.java
  src/main/java/javalab/umc7th_mission/converter/TempConverter.java
  src/main/java/javalab/umc7th_mission/domain/FoodCategory.java
  src/main/java/javalab/umc7th_mission/domain/Member.java
  src/main/java/javalab/umc7th_mission/domain/Mission.java
  src/main/java/javalab/umc7th_mission/domain/Notification.java
  src/main/java/javalab/umc7th_mission/domain/Question.java
  src/main/java/javalab/umc7th_mission/domain/QuestionImage.java
  src/main/java/javalab/umc7th_mission/domain/Region.java
  src/main/java/javalab/umc7th_mission/domain/Review.java
  src/main/java/javalab/umc7th_mission/domain/ReviewImage.java
  src/main/java/javalab/umc7th_mission/domain/Store.java
  src/main/java/javalab/umc7th_mission/domain/Terms.java
  src/main/java/javalab/umc7th_mission/domain/common/BaseEntity.java
  src/main/java/javalab/umc7th_mission/domain/enums/Gender.java
  src/main/java/javalab/umc7th_mission/domain/enums/MemberStatus.java
  src/main/java/javalab/umc7th_mission/domain/enums/MissionStatus.java
  src/main/java/javalab/umc7th_mission/domain/mapping/MemberAddress.java
  src/main/java/javalab/umc7th_mission/domain/mapping/MemberAgree.java
  src/main/java/javalab/umc7th_mission/domain/mapping/MemberMission.java
  src/main/java/javalab/umc7th_mission/domain/mapping/MemberNotification.java
  src/main/java/javalab/umc7th_mission/domain/mapping/MemberPrefer.java
  src/main/java/javalab/umc7th_mission/domain/mapping/StoreAddress.java
  src/main/java/javalab/umc7th_mission/domain/mapping/StoreCategory.java
  src/main/java/javalab/umc7th_mission/repository/MemberMissionRepository/MemberMissionRepository.java
  src/main/java/javalab/umc7th_mission/repository/MemberMissionRepository/MemberMissionRepositoryCustom.java
  src/main/java/javalab/umc7th_mission/repository/MemberMissionRepository/MemberMissionRepositoryImpl.java
  src/main/java/javalab/umc7th_mission/repository/MemberRepository/MemberRepository.java
  src/main/java/javalab/umc7th_mission/repository/MemberRepository/MemberRepositoryCustom.java
  src/main/java/javalab/umc7th_mission/repository/MemberRepository/MemberRepositoryImpl.java
  src/main/java/javalab/umc7th_mission/repository/ReviewRepository/ReviewRepository.java
  src/main/java/javalab/umc7th_mission/repository/ReviewRepository/ReviewRepositoryCustom.java
  src/main/java/javalab/umc7th_mission/repository/ReviewRepository/ReviewRepositoryImpl.java
  src/main/java/javalab/umc7th_mission/repository/StoreRepository/StoreRepository.java
  src/main/java/javalab/umc7th_mission/repository/StoreRepository/StoreRepositoryCustom.java
  src/main/java/javalab/umc7th_mission/repository/StoreRepository/StoreRepositoryImpl.java
  src/main/java/javalab/umc7th_mission/service/TempService/TempCommandService.java
  src/main/java/javalab/umc7th_mission/service/TempService/TempCommandServiceImpl.java
  src/main/java/javalab/umc7th_mission/service/TempService/TempQueryService.java
  src/main/java/javalab/umc7th_mission/service/TempService/TempQueryServiceImpl.java
  src/main/java/javalab/umc7th_mission/web/controller/TempRestController.java
  src/main/java/javalab/umc7th_mission/web/dto/MemberInfoDto.java
  src/main/java/javalab/umc7th_mission/web/dto/TempRequest.java
  src/main/java/javalab/umc7th_mission/web/dto/TempResponse.java
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: Chapter07

#22 [7주차/리키] 워크북 제출합니다.
  build.gradle
  src/main/java/javalab/global/apiPayload/ApiResponse.java
  src/main/java/javalab/global/apiPayload/code/BaseCode.java
  src/main/java/javalab/global/apiPayload/code/BaseErrorCode.java
  src/main/java/javalab/global/apiPayload/code/ErrorReasonDTO.java
  src/main/java/javalab/global/apiPayload/code/ReasonDTO.java
  src/main/java/javalab/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/javalab/global/apiPayload/code/status/SuccessStatus.java
  src/main/java/javalab/global/apiPayload/exception/ExceptionAdvice.java
  src/main/java/javalab/global/apiPayload/exception/GeneralException.java
  src/main/java/javalab/global/apiPayload/exception/handler/TempHandler.java
  src/main/java/javalab/global/entity/BaseEntity.java
  src/main/java/javalab/umc7th_mission/converter/TempConverter.java
  src/main/java/javalab/umc7th_mission/service/TempCommandQueryImpl.java
  src/main/java/javalab/umc7th_mission/service/TempQueryService.java
  src/main/java/javalab/umc7th_mission/service/TempQueryServiceImpl.java
  src/main/java/javalab/umc7th_mission/web/controller/TempRestController.java
  src/main/java/javalab/umc7th_mission/web/dto/TempRequest.java
  src/main/java/javalab/umc7th_mission/web/dto/TempResponse.java
Labels: Chapter07

#32 [8주차/리키] 워크북 제출합니다.
  build.gradle
  src/main/java/javalab/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/javalab/umc7th_mission/converter/TempConverter.java
  src/main/java/javalab/umc7th_mission/domain/Member.java
  src/main/java/javalab/umc7th_mission/domain/Mission.java
  src/main/java/javalab/umc7th_mission/service/TempCommandQueryImpl.java
  src/main/java/javalab/umc7th_mission/service/TempQueryService.java
  src/main/java/javalab/umc7th_mission/service/TempQueryServiceImpl.java
  src/main/java/javalab/umc7th_mission/web/controller/TempRestController.java
  src/main/java/javalab/umc7th_mission/web/dto/TempRequest.java
  src/main/java/javalab/umc7th_mission/web/dto/response/TempResponse.java
Labels: enhancement, Chapter08

#28 [8주차/포비] 워크북 제출합니다.
  build.gradle
  src/main/java/javalab/umc7th_mission/config/SwaggerConfig.java
  src/main/java/javalab/umc7th_mission/controller/MissionController.java
  src/main/java/javalab/umc7th_mission/controller/RegionController.java
  src/main/java/javalab/umc7th_mission/controller/StoreController.java
  src/main/java/javalab/umc7th_mission/controller/UserController.java
  src/main/java/javalab/umc7th_mission/converter/mission/MissionConverter.java
  src/main/java/javalab/umc7th_mission/converter/review/ReviewConverter.java
  src/main/java/javalab/umc7th_mission/converter/user/UserConverter.java
  src/main/java/javalab/umc7th_mission/converter/user/UserFoodCategoryConverter.java
  src/main/java/javalab/umc7th_mission/converter/usermission/UserMissionConverter.java
  src/main/java/javalab/umc7th_mission/domain/Region.java
  src/main/java/javalab/umc7th_mission/domain/Store.java
  src/main/java/javalab/umc7th_mission/domain/User.java
  src/main/java/javalab/umc7th_mission/domain/enums/Gender.java
  src/main/java/javalab/umc7th_mission/domain/enums/MissionStatus.java
  src/main/java/javalab/umc7th_mission/domain/mapping/UserMission.java
  src/main/java/javalab/umc7th_mission/dto/mission/MissionCreateDTO.java
  src/main/java/javalab/umc7th_mission/dto/review/ReviewRequestDTO.java
  src/main/java/javalab/umc7th_mission/dto/user/UserPointDTO.java
  src/main/java/javalab/umc7th_mission/dto/user/UserRequestDTO.java
  src/main/java/javalab/umc7th_mission/dto/user/UserResponseDTO.java
  src/main/java/javalab/umc7th_mission/dto/usermission/UserMissionRequestDTO.java
  src/main/java/javalab/umc7th_mission/global/code/ErrorStatus.java
  src/main/java/javalab/umc7th_mission/global/exception/handler/FoodCategoryHandler.java
  src/main/java/javalab/umc7th_mission/repository/FoodCategoryRepository.java
  src/main/java/javalab/umc7th_mission/repository/RegionRepository.java
  src/main/java/javalab/umc7th_mission/repository/ReviewRepository.java
  src/main/java/javalab/umc7th_mission/repository/StoreRepository.java
  src/main/java/javalab/umc7th_mission/repository/UserFoodCategoryRepository.java
  src/main/java/javalab/umc7th_mission/repository/UserMissionRepository.java
  src/main/java/javalab/umc7th_mission/repository/UserRepository.java
  src/main/java/javalab/umc7th_mission/repository/querydsl/MissionRepository.java
  src/main/java/javalab/umc7th_mission/service/mission/MissionCommandService.java
  src/main/java/javalab/umc7th_mission/service/mission/MissionQueryService.java
  src/main/java/javalab/umc7th_mission/service/region/RegionCommandService.java
  src/main/java/javalab/umc7th_mission/service/region/RegionQueryService.java
  src/main/java/javalab/umc7th_mission/service/store/StoreCommandService.java
  src/main/java/javalab/umc7th_mission/service/store/StoreQueryService.java
  src/main/java/javalab/umc7th_mission/service/user/UserCommandService.java
  src/main/java/javalab/umc7th_mission/service/user/UserQueryService.java
  src/main/java/javalab/umc7th_mission/validation/annotation/ExistCategories.java
  src/main/java/javalab/umc7th_mission/validation/annotation/ExistStore.java
  src/main/java/javalab/umc7th_mission/validation/annotation/IsChallenging.java
  src/main/java/javalab/umc7th_mission/validation/validator/CategoriesExistValidator.java
  src/main/java/javalab/umc7th_mission/validation/validator/MissionChallengingValidator.java
  src/main/java/javalab/umc7th_mission/validation/validator/StoreExistValidator.java
Labels: Chapter08

#30 [8주차/피우] 워크북 제출합니다.
  build.gradle
  src/main/java/javalab/umc7th_mission/apiPayload/code/status/ErrorStatus.java
  src/main/java/javalab/umc7th_mission/config/MultipartJackson2HttpMessageConverter.java
  src/main/java/javalab/umc7th_mission/config/SwaggerConfig.java
  src/main/java/javalab/umc7th_mission/converter/MemberFoodConverter.java
  src/main/java/javalab/umc7th_mission/converter/MissionConverter.java
  src/main/java/javalab/umc7th_mission/converter/RestaurantConverter.java
  src/main/java/javalab/umc7th_mission/converter/ReviewConverter.java
  src/main/java/javalab/umc7th_mission/domain/Mission.java
  src/main/java/javalab/umc7th_mission/domain/Restaurant.java
  src/main/java/javalab/umc7th_mission/domain/Review.java
  src/main/java/javalab/umc7th_mission/domain/ReviewImage.java
  src/main/java/javalab/umc7th_mission/domain/enums/Gender.java
  src/main/java/javalab/umc7th_mission/domain/mapping/MemberMission.java
  src/main/java/javalab/umc7th_mission/repository/FoodCategoryRepository/FoodCategoryRepository.java
  src/main/java/javalab/umc7th_mission/repository/MemberMissionRepository/MemberMissionRepository.java
  src/main/java/javalab/umc7th_mission/repository/MemberRepository/MemberRepository.java
  src/main/java/javalab/umc7th_mission/repository/MissionRepository/MissionRepositoryImpl.java
  src/main/java/javalab/umc7th_mission/repository/RegionRepository/RegionRepository.java
  src/main/java/javalab/umc7th_mission/repository/RestaurantRepository/RestaurantRepository.java
  src/main/java/javalab/umc7th_mission/service/FileService/FileService.java
  src/main/java/javalab/umc7th_mission/service/MissionService/MissionCommandService.java
  src/main/java/javalab/umc7th_mission/service/MissionService/MissionCommandServiceImpl.java
  src/main/java/javalab/umc7th_mission/service/RestaurantService/RestaurantCommandService.java
  src/main/java/javalab/umc7th_mission/service/RestaurantService/RestaurantCommandServiceImpl.java
  src/main/java/javalab/umc7th_mission/service/ReviewService/ReviewCommandService.java
  src/main/java/javalab/umc7th_mission/service/ReviewService/ReviewCommandServiceImpl.java
  src/main/java/javalab/umc7th_mission/validation/annotation/ExistCategory.java
  src/main/java/javalab/umc7th_mission/validation/annotation/ExistChallenge.java
  src/main/java/javalab/umc7th_mission/validation/annotation/ExistMember.java
  src/main/java/javalab/umc7th_mission/validation/annotation/ExistRegion.java
  src/main/java/javalab/umc7th_mission/validation/annotation/ExistRestaurant.java
  src/main/java/javalab/umc7th_mission/validation/validator/CategoryExistValidator.java
  src/main/java/javalab/umc7th_mission/validation/validator/ChallengeExistValidator.java
  src/main/java/javalab/umc7th_mission/validation/validator/MemberExistValidator.java
  src/main/java/javalab/umc7th_mission/validation/validator/RegionExistValidator.java
  src/main/java/javalab/umc7th_mission/validation/validator/RestaurantExistValidator.java
  src/main/java/javalab/umc7th_mission/web/controller/MissionRestController.java
  src/main/java/javalab/umc7th_mission/web/controller/RestaurantRestController.java
  src/main/java/javalab/umc7th_mission/web/controller/ReviewRestController.java
  src/main/java/javalab/umc7th_mission/web/dto/Mission/MissionRequestDTO.java
  src/main/java/javalab/umc7th_mission/web/dto/Mission/MissionResponseDTO.java
  src/main/java/javalab/umc7th_mission/web/dto/Restaurant/RestaurantRequestDTO.java
  src/main/java/javalab/umc7th_mission/web/dto/Restaurant/RestaurantResponseDTO.java
  src/main/java/javalab/umc7th_mission/web/dto/Review/ReviewRequestDTO.java
  src/main/java/javalab/umc7th_mission/web/dto/Review/ReviewResponseDTO.java
  src/main/resources/application.yml
Labels: Chapter08
